AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ConstantStableVerticals trading Lambda.
  Three EventBridge schedules invoke one container-image Lambda
  with different payloads (schwab, tt-ira, tt-individual).

Parameters:
  ScheduleTime:
    Type: String
    Default: "cron(13 16 ? * MON-FRI *)"
    Description: Cron expression for trade trigger (ET).
  DryRun:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Pass dry_run=true to handler (no real orders).

Globals:
  Function:
    Timeout: 360
    MemorySize: 1024

Resources:

  # ---------- Lambda Function ----------
  TradingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures: [x86_64]
      Environment:
        Variables:
          DRY_RUN: !Ref DryRun
          SIM_CACHE_BUCKET: !Ref SimCacheBucket
      Policies:
        # Read all /gamma/* params
        - SSMParameterReadPolicy:
            ParameterName: "gamma/*"
        # Write tokens back after refresh
        - Statement:
            - Effect: Allow
              Action: ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/gamma/*/token_json"
        # S3 access for sim chain cache
        - S3CrudPolicy:
            BucketName: !Ref SimCacheBucket
    Metadata:
      Dockerfile: lambda/Dockerfile
      DockerContext: ..
      DockerTag: latest

  # ---------- Warm-up Schedule (3 min before trade) ----------
  WarmupSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-cs-warmup
      Description: "Warm up Lambda container 3 min before trading"
      State: ENABLED
      ScheduleExpression: "cron(10 16 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "warmup"}'

  # ---------- EventBridge Schedules ----------
  SchwabSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-cs-schwab
      Description: "ConstantStable Schwab account"
      State: ENABLED
      ScheduleExpression: !Ref ScheduleTime
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "schwab"}'

  TtIraSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-cs-tt-ira
      Description: "ConstantStable TT IRA (5WT20360)"
      State: ENABLED
      ScheduleExpression: !Ref ScheduleTime
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "tt-ira"}'

  TtIndividualSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-cs-tt-individual
      Description: "ConstantStable TT Individual (5WT09219)"
      State: ENABLED
      ScheduleExpression: !Ref ScheduleTime
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "tt-individual"}'

  # ---------- Morning Check Schedule ----------
  MorningCheckSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-cs-morning-check
      Description: "Morning equity/drawdown check with email alert"
      State: ENABLED
      ScheduleExpression: "cron(35 9 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "morning-check"}'

  # ---------- S3 Bucket for Sim Chain Cache ----------
  SimCacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gamma-sim-cache
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldChains
            Status: Enabled
            ExpirationInDays: 365

  # ---------- Sim Chain Collection Schedules (ET) ----------
  SimCollectOpen:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-sim-collect-open
      Description: "Sim: collect SPX 0DTE chain at market open"
      State: ENABLED
      ScheduleExpression: "cron(31 9 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "sim-collect", "phase": "open"}'

  SimCollectMid:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-sim-collect-mid
      Description: "Sim: collect SPX chain at midday"
      State: ENABLED
      ScheduleExpression: "cron(0 12 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "sim-collect", "phase": "mid"}'

  SimCollectClose:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-sim-collect-close
      Description: "Sim: collect SPX chain at market close"
      State: ENABLED
      ScheduleExpression: "cron(0 16 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "sim-collect", "phase": "close"}'

  SimCollectClose5:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: gamma-sim-collect-close5
      Description: "Sim: collect SPX 1DTE chain at close+5"
      State: ENABLED
      ScheduleExpression: "cron(5 16 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "America/New_York"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt TradingFunction.Arn
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: '{"account": "sim-collect", "phase": "close5"}'

  # ---------- IAM Role for EventBridge Scheduler ----------
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      Policies:
        - PolicyName: InvokeTradingLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt TradingFunction.Arn

Outputs:
  FunctionArn:
    Description: "Trading Lambda ARN"
    Value: !GetAtt TradingFunction.Arn
  FunctionName:
    Description: "Trading Lambda name (for manual invoke)"
    Value: !Ref TradingFunction
  SimCacheBucketName:
    Description: "S3 bucket for sim chain cache"
    Value: !Ref SimCacheBucket
