name: GW Inspect

on:
  workflow_dispatch:
    inputs:
      days:
        description: "Days back to fetch"
        required: false
        default: "14"
      path:
        description: "Comma-separated endpoint paths"
        required: false
        default: "/rapi/Market/SpxClose,/rapi/SpxClose,/rapi/GetLeoCross"
      start:
        description: "Override start date YYYY-MM-DD (optional)"
        required: false
      end:
        description: "Override end date YYYY-MM-DD (optional)"
        required: false

jobs:
  inspect:
    runs-on: ubuntu-latest
    env:
      GW_BASE: https://gandalf.gammawizard.com
      GW_PATH: ${{ github.event.inputs.path }}
      GW_DUMP_DIR: gw_dump
      # Auth (map your secrets)
      GW_TOKEN: ${{ secrets.GW_TOKEN }}
      GW_VAR2_TOKEN: ${{ secrets.GW_VAR2_TOKEN }}
      GW_EMAIL: ${{ secrets.GW_EMAIL }}
      GW_PASSWORD: ${{ secrets.GW_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Compute window (avoid empty env)
        run: |
          DAYS="${{ github.event.inputs.days }}"
          [ -z "$DAYS" ] && DAYS=14
          START="${{ github.event.inputs.start }}"
          END="${{ github.event.inputs.end }}"
          if [ -z "$START" ]; then START=$(date -u -d "$DAYS days ago" +%F); fi
          if [ -z "$END" ]; then END=$(date -u +%F); fi
          echo "GW_DAYS=$DAYS"   >> $GITHUB_ENV
          echo "GW_START=$START" >> $GITHUB_ENV
          echo "GW_END=$END"     >> $GITHUB_ENV
          echo "Computed window: $START → $END"

      - name: Sanity check secrets
        run: |
          miss=0
          for k in GW_TOKEN GW_EMAIL GW_PASSWORD; do
            if [ -z "${!k:-}" ]; then echo "::warning ::$k is NOT set"; else echo "$k is set"; fi
          done
          # Not fatal—token OR email/password is fine.

      - name: Run inspector
        run: |
          python3 scripts/data/gw_inspect.py

      - name: Upload GW dumps
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gw-dump
          path: gw_dump/*.json
          if-no-files-found: warn
